version: '3.8'

services:
  frontend:
    image: andrewjung03/dreamjournal-frontend:latest
    ports:
      - "8080:5000"
    depends_on:
      - ai_backend
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - AI_SERVICE_BASE=http://ai_backend:6000
      - DB_NAME=${DB_NAME}

  ai_backend:
    image: andrewjung03/dreamjournal-ai_backend:latest
    ports:
      - "6000:6000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}  

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
